### ISSUE TITLE
failed with error: 'ModbusIOException' object has no attribute 'registers'

### ISSUE THREAD

**Issue by mauro-foti** [alexdelprete/ha-sinapsi-alfa#36]
## System Information

version | core-2024.6.4
-- | --
installation_type | Unsupported Third Party Container
dev | false
hassio | false
docker | true
user | abc
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.1.79-Unraid
arch | x86_64
timezone | Europe/Rome
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1391
Downloaded Repositories | 7
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 1
views | 3
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | June 23, 2024 at 4:18 AM
-- | --
current_recorder_run | July 3, 2024 at 7:41 PM
estimated_db_size | 210.50 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I was unable to connect the device

### Reproduction steps

1. add device

### Debug logs

```text
2024-07-03 19:42:30.520 DEBUG (MainThread) [custom_components.sinapsi_alfa.config_flow] Test connection to 10.1.10.25:502
2024-07-03 19:42:30.520 DEBUG (MainThread) [custom_components.sinapsi_alfa.config_flow] Creating API Client
2024-07-03 19:42:30.521 DEBUG (MainThread) [custom_components.sinapsi_alfa.api] Check_Port: opening socket on 10.1.10.25:502 with a 3.0s timeout.
2024-07-03 19:42:30.642 DEBUG (MainThread) [custom_components.sinapsi_alfa.api] Check_Port (SUCCESS): port open on 10.1.10.25:502
2024-07-03 19:42:30.643 DEBUG (MainThread) [custom_components.sinapsi_alfa.api] Get_Mac_Address (SUCCESS): port open on 10.1.10.25:502
2024-07-03 19:42:30.646 DEBUG (MainThread) [custom_components.sinapsi_alfa.api] Get_Mac_Address (SUCCESS): found mac address 244CABE357EC
2024-07-03 19:42:30.646 DEBUG (MainThread) [custom_components.sinapsi_alfa.config_flow] API Client created: calling get data
2024-07-03 19:42:30.646 DEBUG (MainThread) [custom_components.sinapsi_alfa.api] API Client connect to IP: 10.1.10.25 port: 502 timeout: 59.0
2024-07-03 19:42:30.647 DEBUG (MainThread) [custom_components.sinapsi_alfa.api] Check_Port: opening socket on 10.1.10.25:502 with a 3.0s timeout.
2024-07-03 19:42:30.653 DEBUG (MainThread) [custom_components.sinapsi_alfa.api] Check_Port (SUCCESS): port open on 10.1.10.25:502
2024-07-03 19:42:30.654 DEBUG (MainThread) [custom_components.sinapsi_alfa.api] Inverter ready for Modbus TCP connection
2024-07-03 19:42:30.668 DEBUG (MainThread) [custom_components.sinapsi_alfa.api] Modbus TCP Client connected
2024-07-03 19:42:30.668 DEBUG (MainThread) [custom_components.sinapsi_alfa.api] Start Get data (Host: 10.1.10.25 - Port: 502)
2024-07-03 19:42:30.669 DEBUG (SyncWorker_15) [custom_components.sinapsi_alfa.api] (read_modbus_alfa) Key: potenza_prelevata Addr: 2 Type: uint16 DevClass: power
2024-07-03 19:43:29.729 DEBUG (SyncWorker_15) [custom_components.sinapsi_alfa.api] (read_modbus_alfa): failed with error: 'ModbusIOException' object has no attribute 'registers'

raceback (most recent call last):
  File "/config/custom_components/sinapsi_alfa/api.py", line 274, in read_modbus_alfa
    read_data.registers, byteorder=Endian.BIG
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'ModbusIOException' object has no attribute 'registers'
all values are hidden
The above exception was the direct cause of the following exception:
all values are hidden
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/http/forwarded.py", line 210, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/http/data_validator.py", line 70, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/data_entry_flow.py", line 368, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/data_entry_flow.py", line 414, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/data_entry_flow.py", line 517, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sinapsi_alfa/config_flow.py", line 91, in async_step_user
    uid = await self.get_unique_id(name, host, port, scan_interval)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sinapsi_alfa/config_flow.py", line 66, in get_unique_id
    self.api_data = await self.api.async_get_data()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sinapsi_alfa/api.py", line 220, in async_get_data
    result = await self._hass.async_add_executor_job(self.read_modbus_alfa)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sinapsi_alfa/api.py", line 312, in read_modbus_alfa
    raise ModbusError() from modbus_error
custom_components.sinapsi_alfa.api.ModbusError
```

### Diagnostics dump

```
{
  "home_assistant": {
    "installation_type": "Unsupported Third Party Container",
    "version": "2024.6.4",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.12.2",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Rome",
    "os_name": "Linux",
    "os_version": "6.1.79-Unraid",
    "run_as_root": false
  },
  "custom_components": {
    "monitor_docker": {
      "documentation": "https://github.com/ualex73/monitor_docker",
      "version": "1.18",
      "requirements": [
        "aiodocker==0.22.0",
        "python-dateutil==2.9.0"
      ]
    },
    "hacs": {
      "documentation": "https://hacs.xyz/docs/configuration/start",
      "version": "1.34.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "sinapsi_alfa": {
      "documentation": "https://github.com/alexdelprete/ha-sinapsi-alfa",
      "version": "0.2.3",
      "requirements": [
        "pymodbus>=3.5.4",
        "getmac>=0.9.4"
      ]
    },
    "tesla_custom": {
      "documentation": "https://github.com/alandtse/tesla/wiki",
      "version": "3.24.0",
      "requirements": [
        "teslajsonpy==3.12.0"
      ]
    },
    "frigate": {
      "documentation": "https://github.com/blakeblackshear/frigate",
      "version": "5.2.0",
      "requirements": [
        "pytz"
      ]
    },
    "alexa_media": {
      "documentation": "https://github.com/alandtse/alexa_media_player/wiki",
      "version": "4.10.2",
      "requirements": [
        "alexapy==1.27.10",
        "packaging>=20.3",
        "wrapt>=1.14.0"
      ]
    }
  },
  "integration_manifest": {
    "domain": "hacs",
    "name": "HACS",
    "codeowners": [
      "ludeeus"
    ],
    "config_flow": true,
    "dependencies": [
      "http",
      "websocket_api",
      "frontend",
      "persistent_notification",
      "lovelace",
      "repairs"
    ],
    "documentation": "https://hacs.xyz/docs/configuration/start",
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/hacs/integration/issues",
    "requirements": [
      "aiogithubapi>=22.10.1"
    ],
    "version": "1.34.0",
    "is_built_in": false
  },
  "setup_times": {
    "null": {
      "setup": 0.00016804599727038294
    },
    "717128e3417cfe2aa173897337a830c5": {
      "wait_import_platforms": -9.9097184669954,
      "config_entry_setup": 10.341201725997962
    }
  },
  "data": {
    "entry": {
      "data": {
        "token": "**REDACTED**"
      },
      "disabled_by": null,
      "domain": "hacs",
      "entry_id": "717128e3417cfe2aa173897337a830c5",
      "minor_version": 1,
      "options": {
        "experimental": true
      },
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "title": "",
      "unique_id": null,
      "version": 1
    },
    "hacs": {
      "stage": "running",
      "version": "1.34.0",
      "disabled_reason": null,
      "new": false,
      "startup": false,
      "categories": [
        "template",
        "plugin",
        "integration",
        "theme"
      ],
      "renamed_repositories": {
        "custom-components/alexa_media_player": "alandtse/alexa_media_player"
      },
      "archived_repositories": [],
      "ignored_repositories": [],
      "lovelace_mode": "storage",
      "configuration": {
        "appdaemon": false,
        "country": "ALL",
        "debug": false,
        "dev": false,
        "experimental": true,
        "netdaemon": false,
        "python_script": false,
        "release_limit": 5,
        "theme": false
      }
    },
    "custom_repositories": [
      "alexdelprete/ha-sinapsi-alfa"
    ],
    "repositories": [
      {
        "data": {
          "archived": false,
          "authors": [
            "@blakeblackshear"
          ],
          "category": "integration",
          "config_flow": false,
          "default_branch": null,
          "description": "Frigate integration for Home Assistant",
          "domain": "frigate",
          "downloads": 0,
          "etag_repository": "W/\"cadc2c83f587d66f777261bd0bcdf6a1764e7828c445de12022e870e2ccef319\"",
          "etag_releases": null,
          "file_name": "",
          "first_install": false,
          "full_name": "blakeblackshear/frigate-hass-integration",
          "hide": false,
          "has_issues": true,
          "id": "311536795",
          "installed_commit": "5b9f4f7",
          "installed_version": "v5.2.0",
          "installed": true,
          "last_commit": "5b9f4f7",
          "last_updated": "2024-06-14T13:49:30Z",
          "last_version": "v5.2.0",
          "manifest_name": "Frigate",
          "new": false,
          "open_issues": 0,
          "published_tags": [],
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 654,
          "topics": [
            "ai",
            "camera",
            "frigate",
            "nvr",
            "object-detection"
          ]
        },
        "integration_manifest": {},
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": null,
          "hacs": "1.6.0",
          "hide_default_branch": false,
          "homeassistant": "2022.4.5",
          "manifest": {
            "hacs": "1.6.0",
            "name": "Frigate",
            "homeassistant": "2022.4.5"
          },
          "name": "Frigate",
          "persistent_directory": null,
          "render_readme": false,
          "zip_release": false
        },
        "ref": null,
        "paths": {
          "localpath": "/config/custom_components/frigate",
          "local": "/config/custom_components/frigate",
          "remote": "custom_components"
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [
            "@alandtse"
          ],
          "category": "integration",
          "config_flow": false,
          "default_branch": null,
          "description": "Tesla custom integration for Home Assistant. This requires a refresh token be generated by third-party apps to login.",
          "domain": "tesla_custom",
          "downloads": 8869,
          "etag_repository": "W/\"09840ca2551bf45e50ab0e83467dc577c08039111fce0dd73823c4b87b4d42a0\"",
          "etag_releases": null,
          "file_name": "",
          "first_install": false,
          "full_name": "alandtse/tesla",
          "hide": false,
          "has_issues": true,
          "id": "362700564",
          "installed_commit": "d7c8731",
          "installed_version": "v3.24.0",
          "installed": true,
          "last_commit": "d7c8731",
          "last_updated": "2024-07-02T01:39:13Z",
          "last_version": "v3.24.0",
          "manifest_name": "Tesla Custom Integration",
          "new": false,
          "open_issues": 0,
          "published_tags": [],
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 552,
          "topics": [
            "home-assistant-component",
            "tesla"
          ]
        },
        "integration_manifest": {},
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": "tesla_custom.zip",
          "hacs": "1.6.0",
          "hide_default_branch": false,
          "homeassistant": "2023.7.0",
          "manifest": {
            "name": "Tesla",
            "hacs": "1.6.0",
            "homeassistant": "2023.7.0",
            "zip_release": true,
            "filename": "tesla_custom.zip"
          },
          "name": "Tesla",
          "persistent_directory": null,
          "render_readme": false,
          "zip_release": true
        },
        "ref": null,
        "paths": {
          "localpath": "/config/custom_components/tesla_custom",
          "local": "/config/custom_components/tesla_custom",
          "remote": "custom_components"
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [],
          "category": "plugin",
          "config_flow": false,
          "default_branch": null,
          "description": "Build a beautiful Home Assistant dashboard easily",
          "domain": null,
          "downloads": 99380,
          "etag_repository": "W/\"4490a515e708df58d0b1421345ede8933f6f6f1b6a27a65a796a3414276bc886\"",
          "etag_releases": null,
          "file_name": null,
          "first_install": false,
          "full_name": "piitaya/lovelace-mushroom",
          "hide": false,
          "has_issues": true,
          "id": "444350375",
          "installed_commit": "48db88d",
          "installed_version": "v3.5.4",
          "installed": true,
          "last_commit": "efb55ae",
          "last_updated": "2024-06-06T11:11:07Z",
          "last_version": "v3.6.2",
          "manifest_name": null,
          "new": false,
          "open_issues": 0,
          "published_tags": [],
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 3306,
          "topics": [
            "card",
            "mushroom"
          ]
        },
        "integration_manifest": {},
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": "mushroom.js",
          "hacs": null,
          "hide_default_branch": false,
          "homeassistant": "2023.7.0",
          "manifest": {
            "name": "Mushroom",
            "filename": "mushroom.js",
            "homeassistant": "2023.7.0",
            "render_readme": true
          },
          "name": "Mushroom",
          "persistent_directory": null,
          "render_readme": true,
          "zip_release": false
        },
        "ref": null,
        "paths": {
          "localpath": "/config/www/community/lovelace-mushroom",
          "local": "/config/www/community/lovelace-mushroom",
          "remote": null
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [
            "@alexdelprete"
          ],
          "category": "integration",
          "config_flow": true,
          "default_branch": "master",
          "description": "HA Custom Component for Sinapsi Alfa energy monitoring device",
          "domain": "sinapsi_alfa",
          "downloads": 45,
          "etag_repository": "W/\"dd17e9d3fe93f46c65499530545e2d7d9c1f49650db209356790a6cc2575deb4\"",
          "etag_releases": null,
          "file_name": "",
          "first_install": false,
          "full_name": "alexdelprete/ha-sinapsi-alfa",
          "hide": false,
          "has_issues": true,
          "id": "754213636",
          "installed_commit": "1692699",
          "installed_version": "0.2.3",
          "installed": true,
          "last_commit": "1692699",
          "last_updated": "2024-06-28T08:40:58Z",
          "last_version": "0.2.3",
          "manifest_name": "Alfa by Sinapsi",
          "new": false,
          "open_issues": 2,
          "published_tags": [
            "0.2.3",
            "0.2.2",
            "0.2.1",
            "0.2.0",
            "0.1.5"
          ],
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 5,
          "topics": [
            "alfa",
            "home-assistant-component",
            "home-assistant-integration",
            "modbus-tcp",
            "sinapsi",
            "sinapsi-alfa"
          ]
        },
        "integration_manifest": {
          "domain": "sinapsi_alfa",
          "name": "Alfa by Sinapsi",
          "codeowners": [
            "@alexdelprete"
          ],
          "config_flow": true,
          "documentation": "https://github.com/alexdelprete/ha-sinapsi-alfa",
          "integration_type": "hub",
          "iot_class": "local_polling",
          "issue_tracker": "https://github.com/alexdelprete/ha-sinapsi-alfa/issues",
          "loggers": [
            "custom_components.sinapsi_alfa"
          ],
          "requirements": [
            "pymodbus>=3.5.4",
            "getmac>=0.9.4"
          ],
          "single_config_entry": true,
          "version": "0.1.0"
        },
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": "sinapsi_alfa.zip",
          "hacs": null,
          "hide_default_branch": false,
          "homeassistant": "2024.3.0",
          "manifest": {
            "name": "Alfa by Sinapsi",
            "homeassistant": "2024.3.0",
            "render_readme": true,
            "zip_release": true,
            "filename": "sinapsi_alfa.zip"
          },
          "name": "Alfa by Sinapsi",
          "persistent_directory": null,
          "render_readme": true,
          "zip_release": true
        },
        "ref": "0.2.3",
        "paths": {
          "localpath": "/config/custom_components/sinapsi_alfa",
          "local": "/config/custom_components/sinapsi_alfa",
          "remote": "custom_components/sinapsi_alfa"
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [
            "@alandtse",
            "@keatontaylor"
          ],
          "category": "integration",
          "config_flow": false,
          "default_branch": null,
          "description": "This is a custom component to allow control of Amazon Alexa devices in Home Assistant using the unofficial Alexa API.",
          "domain": "alexa_media",
          "downloads": 40371,
          "etag_repository": "W/\"55592bb06919ffcd155b5caa93a868b5498712ca90d2fa19f4d56cbbd831250c\"",
          "etag_releases": null,
          "file_name": "",
          "first_install": false,
          "full_name": "alandtse/alexa_media_player",
          "hide": false,
          "has_issues": true,
          "id": "139664351",
          "installed_commit": "50a03cc",
          "installed_version": "v4.10.2",
          "installed": true,
          "last_commit": "7ea65fc",
          "last_updated": "2024-06-30T06:24:54Z",
          "last_version": "v4.10.2",
          "manifest_name": "Alexa Media Player",
          "new": false,
          "open_issues": 0,
          "published_tags": [],
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 1353,
          "topics": [
            "alexa"
          ]
        },
        "integration_manifest": {},
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": "alexa_media.zip",
          "hacs": null,
          "hide_default_branch": false,
          "homeassistant": "2024.2.0b0",
          "manifest": {
            "name": "Alexa Media Player",
            "zip_release": true,
            "filename": "alexa_media.zip",
            "homeassistant": "2024.2.0b0"
          },
          "name": "Alexa Media Player",
          "persistent_directory": null,
          "render_readme": false,
          "zip_release": true
        },
        "ref": null,
        "paths": {
          "localpath": "/config/custom_components/alexa_media",
          "local": "/config/custom_components/alexa_media",
          "remote": "custom_components"
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [
            "@ualex73"
          ],
          "category": "integration",
          "config_flow": false,
          "default_branch": null,
          "description": "Monitor Docker containers from Home Assistant",
          "domain": "monitor_docker",
          "downloads": 0,
          "etag_repository": "W/\"2f07f57f8ff475f46e4fa484fe320b2b46569e7ca37d5ab2001f192c2c96a422\"",
          "etag_releases": null,
          "file_name": "",
          "first_install": false,
          "full_name": "ualex73/monitor_docker",
          "hide": false,
          "has_issues": true,
          "id": "272140589",
          "installed_commit": "cae359d",
          "installed_version": "1.19",
          "installed": true,
          "last_commit": "cae359d",
          "last_updated": "2024-06-28T14:03:06Z",
          "last_version": "1.19",
          "manifest_name": "Monitor Docker",
          "new": false,
          "open_issues": 0,
          "published_tags": [],
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 267,
          "topics": [
            "docker"
          ]
        },
        "integration_manifest": {},
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": null,
          "hacs": null,
          "hide_default_branch": false,
          "homeassistant": null,
          "manifest": {
            "name": "Monitor Docker",
            "render_readme": true
          },
          "name": "Monitor Docker",
          "persistent_directory": null,
          "render_readme": true,
          "zip_release": false
        },
        "ref": null,
        "paths": {
          "localpath": "/config/custom_components/monitor_docker",
          "local": "/config/custom_components/monitor_docker",
          "remote": "custom_components"
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [
            "@ludeeus"
          ],
          "category": "integration",
          "config_flow": false,
          "default_branch": null,
          "description": "HACS gives you a powerful UI to handle downloads of all your custom needs.",
          "domain": "hacs",
          "downloads": 676646,
          "etag_repository": "W/\"d551bfe84123456ecb5af05308ea95f31a9d0c852bd635d1a9194c87f5e57528\"",
          "etag_releases": null,
          "file_name": "",
          "first_install": false,
          "full_name": "hacs/integration",
          "hide": false,
          "has_issues": true,
          "id": "172733314",
          "installed_commit": "7d46a52",
          "installed_version": "1.34.0",
          "installed": true,
          "last_commit": "1d5e9a6",
          "last_updated": "2024-07-03T13:18:44Z",
          "last_version": "1.34.0",
          "manifest_name": "HACS",
          "new": false,
          "open_issues": 0,
          "published_tags": [],
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 4869,
          "topics": [
            "community",
            "package-manager"
          ]
        },
        "integration_manifest": {},
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": "hacs.zip",
          "hacs": "0.19.0",
          "hide_default_branch": true,
          "homeassistant": "2023.6.0",
          "manifest": {
            "name": "HACS",
            "zip_release": true,
            "hide_default_branch": true,
            "homeassistant": "2023.6.0",
            "hacs": "0.19.0",
            "filename": "hacs.zip"
          },
          "name": "HACS",
          "persistent_directory": null,
          "render_readme": false,
          "zip_release": true
        },
        "ref": null,
        "paths": {
          "localpath": "/config/custom_components/hacs",
          "local": "/config/custom_components/hacs",
          "remote": "custom_components"
        }
      }
    ],
    "rate_limit": {
      "resources": {
        "core": {
          "limit": 5000,
          "used": 6,
          "remaining": 4994,
          "reset": 1720032960
        },
        "search": {
          "limit": 30,
          "used": 0,
          "remaining": 30,
          "reset": 1720029433
        },
        "graphql": {
          "limit": 5000,
          "used": 0,
          "remaining": 5000,
          "reset": 1720032973
        },
        "integration_manifest": {
          "limit": 5000,
          "used": 0,
          "remaining": 5000,
          "reset": 1720032973
        },
        "source_import": {
          "limit": 100,
          "used": 0,
          "remaining": 100,
          "reset": 1720029433
        },
        "code_scanning_upload": {
          "limit": 1000,
          "used": 0,
          "remaining": 1000,
          "reset": 1720032973
        },
        "actions_runner_registration": {
          "limit": 10000,
          "used": 0,
          "remaining": 10000,
          "reset": 1720032973
        },
        "scim": {
          "limit": 15000,
          "used": 0,
          "remaining": 15000,
          "reset": 1720032973
        },
        "dependency_snapshots": {
          "limit": 100,
          "used": 0,
          "remaining": 100,
          "reset": 1720029433
        }
      },
      "rate": {
        "limit": 5000,
        "used": 6,
        "remaining": 4994,
        "reset": 1720032960
      }
    }
  }
}
```

**Comment by alexdelprete** [comment]
That error usually indicates a communication issue with the device. Does the Alfa have a good wifi connection?
